using System;
using System.Collections.Generic;
using System.IO;

namespace MCSong
{
    class MessagesDB
    {
        public static void Load(Level l)
        {
            string path = "db/mb/" + l.name + ".txt";
            if (File.Exists(path))
            {
                Level.MessageBlock mb = new Level.MessageBlock();
                foreach (string line in File.ReadAllLines(path))
                {
                    if (!String.IsNullOrEmpty(line) && !line.StartsWith("#"))
                    {
                        string[] x = line.Split('|');
                        mb.X = ushort.Parse(x[0]);
                        mb.Y = ushort.Parse(x[1]);
                        mb.Z = ushort.Parse(x[2]);
                        mb.type = int.Parse(x[3]);
                        mb.message = x[4];
                        if (Block.mb(l.GetTile(mb.X, mb.Y, mb.Z)))
                            l.MBList.Add(mb);
                    }
                }
            }
            else
            {
                l.MBList = new List<Level.MessageBlock>();
                Save(l);
            }
        }

        public static void Save(Level l)
        {
            if (!Directory.Exists("db/mb/"))
                Directory.CreateDirectory("db/mb/");
            StreamWriter sw = new StreamWriter(File.Create("db/mb/" + l.name + ".txt"));
            sw.WriteLine("# Generated by the MCSong Flatfile System");
            sw.WriteLine("# MessagesDB for " + l.name);
            sw.WriteLine();
            if (l.MBList.Count > 0)
                foreach (Level.MessageBlock mb in l.MBList)
                {
                    sw.WriteLine(mb.X + "|" + mb.Y + "|" + mb.Z + "|" + mb.type + "|" + mb.message);
                }
            sw.WriteLine("# Saved: " + DateTime.Now.ToString());
            sw.Flush();
            sw.Close();
            sw.Dispose();
        }
    }
}
